# === Этап сборки фронта ===
FROM node:20-alpine AS builder

WORKDIR /app
# 1️⃣ Копируем только package.json и lock-файл
COPY package*.json ./

# 2️⃣ Устанавливаем зависимости
RUN npm install

# 3️⃣ Копируем остальной проект
COPY . .

# 4️⃣ Сборка
RUN npm run build

# === Этап nginx-сервера ===
FROM nginx:1.25-alpine AS production

# Копируем кастомный конфиг в nginx
COPY nginx/film.conf /etc/nginx/conf.d/film.conf

# Кладём собранные статики в специальную папку для проекта film
COPY --from=builder /app/dist /usr/share/nginx/film/
