version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: film_frontend
    ports:
      - "8080:80"
    networks:
      - filmnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: film_backend
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    networks:
      - filmnet

  nginx-proxy:
    image: nginx:alpine
    container_name: film_nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - filmnet


  postgres:
    image: postgres:15-alpine
    container_name: film_postgres
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    networks:
      - filmnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: film_pgadmin
    restart: always
    ports:
      - "8081:80"
    env_file:
      - ./backend/.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - filmnet

volumes:
  pg_data:
  pgadmin_data:

networks:
  filmnet:
